return {
	{
		name = "Working_Mode",
		desc = "激光器工作模式",
		vt = "int",
		cmd = "state",
		decode_mode = 1,
	},
	{
		name = "Working_Frequency",
		desc = "激光器工作频率",
		vt = "int",
		unit = "khz",
		rate = 0.001,
		cmd = "tf",
		rp = "trigfreq",
		decode_mode = 1,
	},		
	{
		name = "Trigger_Mode",
		desc = "激光器触发模式",
		vt = "int",
		cmd = "trig",
		decode_mode = 1,
	},
	{
		name = "Scaling_down_Setting",
		desc = "分频设置",
		vt = "int",
		cmd = "eaom_div",
		rp = "eaomdiv",
		decode_mode = 1,
	},
	{
		name = "Power_Settings",
		desc = "功率设置",
		vt = "int",
		unit = "%",
		rate = 0.1,
		cmd  ="pf",
		rp = "powerfactor",
		decode_mode = 1,
    },
	{
		name = "Report_Errors",
		desc = "报错",
		vt = "int",
		cmd = "geterrors",
		decode_mode = 1,
	},
-- 	{
-- 		name = "Command_Table",
-- 		desc = "显示激光器命令表",
-- 		vt = "string",
-- 		cmd = "display\n",
-- 		decode_mode = 0,
-- 	},
	{
		name = "Run_Status",
		desc = "显示激光器运行状态",
		vt = "string",
		cmd = "k\n",
		decode_mode = 0,
	},
	{
		name = "Soft_Version",
		desc = "激光器软件版本号",
		vt = "string",
		cmd = "Copyright",
		decode_mode = 1,
	},
	{
		name = "ontime",
		desc = "State 2状态总时长",
		vt = "string",
		cmd = "ontime",
		decode_mode = 1,
	},
	{
		name = "sleeptime",
		desc = "State 1状态总时长",
		vt = "string",
		cmd = "sleeptime",
		decode_mode = 1,
	},
	{
		name = "standbytime",
		desc = "State 0状态总时长",
		vt = "string",
		cmd = "standbytime",
		decode_mode = 1,
	},
	{
		name = "powerontime",
		desc = "激光器开机总时长",
		vt = "string",
		cmd = "powerontime",
		decode_mode = 1,
	},
}

